name: Generate Blog List

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install gray-matter

      - name: Generate blog list
        run: node src/content/blog/generate-list.js

      - name: Commit and push list.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/content/blog/list.json
          git diff --cached --quiet || git commit -m "🔄 Auto-update blog list"
          git push
