name: Auto-generate list.json & my-sitemap.xml

on:
  push:
    paths:
      - 'src/content/blog/**.md'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 2️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install gray-matter

      # 4️⃣ Generate list.json
      - name: Generate list.json
        run: node src/content/blog/generate-list.js

      # 5️⃣ Generate my-sitemap.xml in root
      - name: Generate my-sitemap.xml
        run: node src/content/blog/generate-sitemap.js

      # 6️⃣ Commit & Push changes
      - name: Commit & Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add src/content/blog/list.json my-sitemap.xml
          git commit -m "Auto-update list.json & my-sitemap.xml [skip ci]" || echo "No changes"
          git push https://$GH_PAT@github.com/MyAstrology/services.git HEAD:main
