name: Generate Blog & Sitemaps

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install gray-matter fs-extra path

      - name: Generate blog list
        run: node src/content/blog/generate-list.js

      - name: Generate blog sitemap
        run: node src/content/blog/generate-sitemap.js

      - name: Generate image sitemap
        run: node src/content/blog/generate-image-sitemap.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add src/content/blog/list.json my-sitemap.xml image-sitemap.xml

          # Only commit if changes exist
          git diff --cached --quiet || git commit -m "🔄 Auto-update blog list & sitemaps"

          # Pull remote changes to avoid conflicts
          git pull --rebase origin main || true

          # Push updated files
          git push origin main
