name: Generate Image Sitemap

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate image sitemap
        run: node src/content/blog/generate-image-sitemap.js
run: node src/content/assist/generate-image-sitemap.js
run: node src/content/gallery/generate-image-sitemap.js
run: node src/content/images/generate-image-sitemap.js

      - name: Commit and push sitemap
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add image-sitemap.xml
          git diff --cached --quiet || git commit -m "🔄 Auto-update image sitemap"
          git push origin main --force
